### Create client
GET http://localhost:8801/create?name=Test

### Get client info
GET http://localhost:8801/get

### Update client name
GET http://localhost:8801/update/1?name=TestUpdate

### Get info about client with id 1
GET http://localhost:8801/get/1

### Delete client with id 1
GET http://localhost:8801/delete/1





