
### Create account for the client
GET http://localhost:8802/create?client_id=1

### Put some money to the account
GET http://localhost:8802/fund/1?sum=1000

### Spend some money
GET http://localhost:8802/checkout/1?sum=100

### Get info about the account
GET http://localhost:8802/get/1

